# Generated by Django 5.0.2 on 2024-03-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(default='Information is not available', max_length=200, null=True),
        ),
    ]
